# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zA8pOu6_E5wdyPS2z8na20iDiYoN0zsA
"""

import torch
import seaborn as sns
import matplotlib.pyplot as plt

df = sns.load_dataset('diamonds')

df.head()

print(f"data shape is :{df.shape}--->(rows,columns)")

df.info()

# Data Visualization - Histogram of Price (Continuous Target)
plt.figure(figsize=(8,6))
sns.histplot(df['price'], kde=True)
plt.title("Price Distribution")
plt.show()

plt.figure(figsize=(8,6))
sns.histplot(df['color'],kde=True)
plt.show()

plt.figure(figsize=(8,6))
sns.scatterplot(data=df, x='carat',y='price')
plt.grid()
plt.show()

plt.figure(figsize=(8,6))
sns.countplot(data=df, x='cut')

"""#Bivarite Analysis
- Two varaibles at a time
"""

sns.barplot(data=df, x='cut',y='price',palette='Set3')
plt.grid()
plt.show()

sns.boxplot(data=df, x='cut',y='price',palette='Set1')
plt.grid()
plt.show()

sns.countplot(data=df, x='cut',hue='clarity')

